name: algebra
version: 0.1.0.0
license: ISC

ghc-options: -Wall -Wno-name-shadowing

dependencies:
    - base >4 && <5
    - transformers
    - mtl
    - criterion
    - deepseq

library:
  source-dirs: .
  exposed-modules:
      - Algebra
      - Algebra2
      - Filesystem
  other-modules: []


tests:
    doctest:
        main: doctest-driver.hs
        source-dirs: .
        dependencies:
            - doctest
            - doctest-discover
        other-modules: []
