name: algebra
version: 0.1.0.0
license: ISC

ghc-options: -Wall -Wno-name-shadowing

dependencies:
    - base >4 && <5
    - transformers
    - mtl
    - deepseq
    - directory
    - filepath
    - text
    - array

library:
  source-dirs: .
  exposed-modules:
      - Algebra
      - Algebra2
      - Expr
      - Filesystem
      - Zip
      - Cartesian
  other-modules: []

tests:
    doctest:
        main: doctest-driver.hs
        source-dirs: .
        dependencies:
            - doctest
            - doctest-discover
        other-modules: []

benchmarks:
    criterion:
        main: Bench.hs
        dependencies:
            - criterion
            - statistics
        ghc-options: -O2 -w
        other-modules:
            - Algebra
